"""Database models."""

from maya_db.models.google_integration import (
    GoogleConnection,
    OAuthPkceState,
    OperatorGoogleIdentity,
)
from maya_db.models.operator import OperatorUser
from maya_db.models.operator_voice import (
    OperatorConversationMessage,
    OperatorConversationSession,
    OperatorPersonalities,
    OperatorVoiceSettings,
)
from maya_db.models.voice_room import (
    VoiceRoom,
    VoiceRoomMember,
    VoiceRoomMessage,
    VoiceRoomVoiceQueue,
)
from maya_db.models.arena import (
    ArenaArtifact,
    ArenaBattle,
    ArenaCandidate,
    ArenaSession,
    ArenaVote,
    Battle,
    Candidate,
)
from maya_db.models.image_job import ImageJobTable
from maya_db.models.image_workflow import ImageWorkflowRow
from maya_db.models.feeds import (
    Channel,
    ChannelTag,
    CollectionSummary,
    Comment,
    CommentSnapshot,
    FeedAnalysis,
    Follow,
    IntelItem,
    KnowledgeItem,
    Notification,
    OperatorPreferences,
    OperatorSourceToken,
    Person,
    PersonChannel,
    Subscription,
    TagNode,
    Video,
    VideoIntelLink,
    VideoSimilarity,
    VideoTag,
)
from maya_db.models.music import (
    MusicArtist,
    MusicGenre,
    MusicPlatformLink,
    MusicRelease,
    MusicReleaseTrack,
    MusicTrack,
    MusicTrackArtist,
)
from maya_db.models.registry import EvalRun, ModelRelease
from maya_db.models.research import (
    BrowserHistoryEmbedding,
    ResearchRun,
    ResearchSentiment,
    ResearchSource,
    ResearchTopicEmbedding,
)
from maya_db.models.capture import BrowserCaptureOutbox, Capture
from maya_db.models.kb import AtomicNote, NoteEdge, NoteImage

__all__ = [
    "AtomicNote",
    "NoteEdge",
    "NoteImage",
    "BrowserCaptureOutbox",
    "Capture",
    "GoogleConnection",
    "OAuthPkceState",
    "OperatorGoogleIdentity",
    "OperatorUser",
    "OperatorVoiceSettings",
    "OperatorPersonalities",
    "OperatorConversationSession",
    "OperatorConversationMessage",
    "VoiceRoom",
    "VoiceRoomMember",
    "VoiceRoomMessage",
    "VoiceRoomVoiceQueue",
    "ArenaArtifact",
    "ArenaBattle",
    "ArenaCandidate",
    "ArenaSession",
    "ArenaVote",
    "Battle",
    "Candidate",
    "ImageJobTable",
    "ImageWorkflowRow",
    "Channel",
    "ChannelTag",
    "CollectionSummary",
    "Comment",
    "CommentSnapshot",
    "EvalRun",
    "FeedAnalysis",
    "Follow",
    "IntelItem",
    "KnowledgeItem",
    "ModelRelease",
    "MusicArtist",
    "MusicGenre",
    "MusicPlatformLink",
    "MusicRelease",
    "MusicReleaseTrack",
    "MusicTrack",
    "MusicTrackArtist",
    "Notification",
    "OperatorPreferences",
    "OperatorSourceToken",
    "Person",
    "PersonChannel",
    "Subscription",
    "TagNode",
    "Video",
    "VideoIntelLink",
    "VideoSimilarity",
    "VideoTag",
    "BrowserHistoryEmbedding",
    "ResearchRun",
    "ResearchSentiment",
    "ResearchSource",
    "ResearchTopicEmbedding",
    "BrowserCaptureOutbox",
    "Capture",
]
